const GET_COINS_TABLE = 'GET_COINS_TABLE';
const GET_COINS_TABLE_SUCCESS = 'GET_COINS_TABLE_SUCCESS';
const GET_COINS_TABLE_FAILURE = 'GET_COINS_TABLE_FAILURE';

const GET_COIN = 'GET_COIN';
const GET_COIN_SUCCESS = 'GET_COIN_SUCCESS';
const GET_COIN_FAILURE = 'GET_COIN_FAILURE';

export {
  GET_COINS_TABLE,
  GET_COINS_TABLE_SUCCESS,
  GET_COINS_TABLE_FAILURE,
  GET_COIN,
  GET_COIN_SUCCESS,
  GET_COIN_FAILURE
};